handle milestone due date unset
peewee.ProgrammingError: column "due_date" is of type date but expression is of type integer
LINE 1: ...UES ('2017-04-22T01:29:01.211765'::timestamp, '', 0, 166, 'a...
                                                             ^
HINT:  You will need to rewrite or cast the expression.